# Generated by Django 3.2.16 on 2023-02-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalityApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='apptitude_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(max_length=250)),
                ('questions', models.CharField(max_length=250)),
                ('option1', models.CharField(max_length=250)),
                ('option2', models.CharField(max_length=250)),
                ('option3', models.CharField(max_length=250)),
                ('option4', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=250)),
            ],
        ),
    ]
