# Generated by Django 3.2.16 on 2023-03-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalityApp', '0003_personality_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250)),
                ('salary', models.CharField(max_length=250)),
                ('place', models.CharField(max_length=250)),
            ],
        ),
    ]
