# Generated by Django 3.2.16 on 2023-03-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalityApp', '0004_job_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_details',
            name='jobid',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
