# Generated by Django 3.2.16 on 2023-03-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalityApp', '0005_job_details_jobid'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=250)),
                ('job_id', models.IntegerField()),
                ('qualification', models.CharField(max_length=250)),
                ('skills', models.CharField(max_length=250)),
            ],
        ),
    ]
