# Generated by Django 3.2.16 on 2022-12-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CattleServerApp', '0002_alter_accounts_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('is_enabled', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
    ]
