# Generated by Django 3.2.16 on 2022-12-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CattleServerApp', '0003_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
    ]
