# Generated by Django 3.2.16 on 2023-03-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CattleServerApp', '0004_remove_doctor_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('food_detals', models.CharField(max_length=255)),
                ('lifeTime', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=150)),
                ('origin', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=150)),
                ('is_enabled', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'breeds',
            },
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'food_detals',
            },
        ),
    ]
