# Generated by Django 3.2.16 on 2023-03-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CattleServerApp', '0005_breed_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='food_detals',
            new_name='food_details',
        ),
    ]
