# Generated by Django 3.2.18 on 2023-02-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepressionApp', '0002_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom_ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Userid', models.IntegerField()),
                ('Questionid', models.IntegerField()),
                ('Answer', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'temp_answer',
                'managed': True,
            },
        ),
    ]
