# Generated by Django 3.2.18 on 2023-02-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepressionApp', '0003_custom_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_enabled',
            field=models.IntegerField(default=1),
        ),
    ]
