# Generated by Django 3.2.18 on 2023-02-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepressionApp', '0005_auto_20230222_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='age',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
