# Generated by Django 3.2.18 on 2023-02-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DepressionApp', '0006_accounts_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='age',
        ),
    ]
