# Generated by Django 3.2.18 on 2023-02-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepressionApp', '0007_remove_accounts_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='age',
            field=models.CharField(default=12, max_length=15),
            preserve_default=False,
        ),
    ]
