# Generated by Django 3.2.18 on 2023-02-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepressionApp', '0008_accounts_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
