# Generated by Django 3.2.18 on 2023-02-24 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DepressionApp', '0009_questions_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='age',
            new_name='dateofbirth',
        ),
    ]
