# Generated by Django 3.2.18 on 2023-02-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepressionApp', '0010_rename_age_accounts_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='option3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option4',
            field=models.IntegerField(default=0),
        ),
    ]
