# Generated by Django 3.2.18 on 2023-02-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepressionApp', '0014_alter_questions_option3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pr_question', models.CharField(max_length=255)),
                ('Pr_option1', models.CharField(max_length=255)),
                ('Pr_option2', models.CharField(max_length=255)),
                ('Pr_option3', models.CharField(default='None', max_length=255)),
                ('Pr_option4', models.CharField(default='None', max_length=255)),
                ('Pr_correct_option', models.CharField(default='None', max_length=255)),
                ('Pr_category', models.CharField(max_length=30)),
                ('Pr_is_enabled', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'progress_questions',
                'managed': True,
            },
        ),
    ]
