# Generated by Django 3.2.18 on 2023-02-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepressionApp', '0015_progress_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggetions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Suggetion', models.CharField(max_length=255)),
                ('is_enabled', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'suggetion',
                'managed': True,
            },
        ),
    ]
