# Generated by Django 3.2.18 on 2023-02-27 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DepressionApp', '0016_suggetions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suggetions',
            new_name='Suggestions',
        ),
        migrations.RenameField(
            model_name='suggestions',
            old_name='Suggetion',
            new_name='Suggestion',
        ),
    ]
