# Generated by Django 3.2.18 on 2023-02-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepressionApp', '0017_auto_20230227_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='Title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
